export const images = [
    { id: 'none', name: 'No Background', url: '', guideUrl: '' },
    { id: 'turtle', name: 'Turtle', url: '/colored/turtle.jpg', guideUrl: '/grayscale/turtle.jpg' },
    { id: 'tiger', name: 'Tiger', url: '/colored/tiger.jpg', guideUrl: '/grayscale/tiger.jpg' },
    { id: 'sheep', name: 'Sheep', url: '/colored/sheep.jpg', guideUrl: '/grayscale/sheep.jpg' },
    { id: 'rabbit', name: 'Rabbit', url: '/colored/rabbit.jpg', guideUrl: '/grayscale/rabbit.jpg' },
    { id: 'pig', name: 'Pig', url: '/colored/pig.jpg', guideUrl: '/grayscale/pig.jpg' },
    { id: 'penguin', name: 'Penguin', url: '/colored/penguin.jpg', guideUrl: '/grayscale/penguin.jpg' },
    { id: 'panda', name: 'Panda', url: '/colored/panda.jpg', guideUrl: '/grayscale/panda.jpg' },
    { id: 'owl', name: 'Owl', url: '/colored/owl.jpg', guideUrl: '/grayscale/owl.jpg' },
    { id: 'lion', name: 'Lion', url: '/colored/lion.jpg', guideUrl: '/grayscale/lion.jpg' },
    { id: 'hamster', name: 'Hamster', url: '/colored/hamster.jpg', guideUrl: '/grayscale/hamster.jpg' },
    { id: 'frog', name: 'Frog', url: '/colored/frog.jpg', guideUrl: '/grayscale/frog.jpg' },
    { id: 'duck', name: 'Duck', url: '/colored/duck.jpg', guideUrl: '/grayscale/duck.jpg' },
    { id: 'deer', name: 'Deer', url: '/colored/deer.jpg', guideUrl: '/grayscale/deer.jpg' },
    { id: 'cow', name: 'Cow', url: '/colored/cow.jpg', guideUrl: '/grayscale/cow.jpg' },
    { id: 'horse', name: 'Horse', url: '/colored/horse.jpg', guideUrl: '/grayscale/horse.jpg' },
    { id: 'elephant', name: 'Elephant', url: '/colored/elephant.jpg', guideUrl: '/grayscale/elephant.jpg' },
    { id: 'giraffe', name: 'Giraffe', url: '/colored/giraffe.jpg', guideUrl: '/grayscale/giraffe.jpg' },
    { id: 'fish', name: 'Fish', url: '/colored/fish.jpg', guideUrl: '/grayscale/fish.jpg' },
    { id: 'whale', name: 'Whale', url: '/colored/whale.jpg', guideUrl: '/grayscale/whale.jpg' },
    { id: 'bird', name: 'Bird', url: '/colored/bird.jpg', guideUrl: '/grayscale/bird.jpg' },
    { id: 'cat', name: 'Cat', url: '/colored/cat.jpg', guideUrl: '/grayscale/cat.jpg' },
    { id: 'dog', name: 'Dog', url: '/colored/dog.jpg', guideUrl: '/grayscale/dog.jpg' }
  ];
